# Generated by Django 5.1.6 on 2025-02-18 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0002_baseuser_created_at_baseuser_deleted_at_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='baseuser',
            managers=[
            ],
        ),
        migrations.AddField(
            model_name='baseuser',
            name='local_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
