# Generated by Django 5.1.6 on 2025-02-11 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='uuid',
            field=models.UUIDField(editable=False, null=True, unique=True),
        ),
    ]
