# Generated by Django 5.1.6 on 2025-02-11 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0003_alter_tenant_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant',
            name='uuid',
            field=models.CharField(editable=False, max_length=36, null=True, unique=True),
        ),
    ]
