# Generated by Django 5.1.6 on 2025-02-18 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0007_customer_deleted_at_customer_is_deleted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='local_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='department',
            name='local_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='local_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tenant',
            name='local_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
